// js/translations.js
const translations = {
    'fr': {
        // --- Textes généraux ---
        'hero-title': "Noms Français le long de la côte Australienne", 'hero-subtitle': "Les toponymes issus des voyages de d’Entrecasteaux (1791-1794) et Baudin (1800-1804)",
        'nav-home': "Accueil", 'nav-map-dentre': "Carte Interactive : d'Entrecasteaux", 'nav-map-baudin': "Carte Interactive : Baudin", 'nav-resources': "Ressources",
        'footer-text': '&copy; 2024 - Dany Bréelle - Projet "Noms Français le long de la côte Australienne"',

        // --- Page d'accueil (index.html) ---
        'intro-title': "Introduction",
        'intro-p1': "Ce projet explore l'héritage distinctif de la toponymie française le long des côtes australiennes, retraçant comment ces noms de lieux — dont beaucoup sont encore visibles sur les cartes modernes — reflètent les histoires superposées de l'exploration européenne. Dans le contexte du lien profond et durable des peuples des Premières Nations avec leur Territoire, les pratiques de dénomination françaises côtoient celles des navigateurs néerlandais et britanniques, formant un palimpseste complexe de sens et de mémoire.",
        'intro-p2': "En se concentrant sur les plus de 670 sites nommés lors des expéditions de d’Entrecasteaux et de Baudin, l'étude met en lumière une perspective française unique qui enrichit notre compréhension de l'histoire côtière de l'Australie et de ses contextes mondiaux et locaux enchevêtrés.",
        'intro-p3': "<em>La recherche présentée sur ce site a été soutenue par la RGSSA, la WAHF, …</em>",
        'map-title-freycinet': "Carte de Freycinet, 1812", 'map-title-beautemps': "Carte de Beautemps-Beaupré, 1807",

        // --- Page Carte d'Entrecasteaux ---
        'dentre-title': "Carte Interactive : L'Expédition d'Entrecasteaux (1791-1793)",
        'dentre-desc': "Explorez les noms de lieux donnés lors de l'expédition d'Antoine Bruny d'Entrecasteaux, qui a cartographié en grand détail les côtes de la Tasmanie à la recherche de La Pérouse. Cliquez sur un marqueur pour découvrir plus d'informations.",
        'dentre-text-p1': "Le premier objectif de l'expédition d'Entrecasteaux, la recherche de La Pérouse, disparu, s'est soldé par un échec. Aucune trace de ses deux navires ou de leur équipage ne fut trouvée sur les îles du Pacifique occidental qu'ils explorèrent. Cependant, le second volet de la mission de l'expédition, la cartographie des côtes des Terres Australes encore partiellement inconnues des Européens, fut une grande réussite. Ces découvertes redonnèrent espoir et motivation à l'équipage après une traversée difficile de l'océan Indien austral dans une mer agitée. La nomenclature laissée par d'Entrecasteaux le long des côtes de ce qui est aujourd'hui la Tasmanie et l'Australie-Occidentale rend hommage à son équipage méritant qui a rendu ces découvertes possibles, ainsi qu'au voyage en général.",
        'dentre-text-p2': "Les côtes est de la Terre de Van Diemen (Tasmanie) furent visitées en avril-mai 1792 et de nouveau fin janvier-février 1793, et les côtes sud-ouest de la Nouvelle-Hollande (Australie-Occidentale) fin décembre 1792 - janvier 1793.",
        'dentre-text-p3': "68 lieux furent nommés le long de ces côtes par d’Entrecasteaux et, après le voyage, pour quelques-uns d'entre eux, par Rossel*. Ils ont été subdivisés en deux sections : les noms sur les côtes est de la Terre de Van Diemen (Tasmanie), visitées en avril-mai 1792 et de nouveau fin janvier-février 1793, et les noms le long des côtes sud-ouest de la Nouvelle-Hollande (Australie-Occidentale) fin décembre 1792 - janvier 1793.",
        'dentre-text-p4': "Ce ne fut pas une tâche facile pour le commandant de trouver un terrain d'entente entre les questions nautiques, le calendrier de son itinéraire, les travaux de relevé et d'hydrographie, et l'intérêt de ses savants pour l'histoire naturelle et la découverte de nouvelles espèces. Les naturalistes se plaignaient souvent que les officiers avaient la priorité (par exemple, eux, les savants, devaient attendre bien plus longtemps que les officiers pour le canotier) et les relations entre officiers et savants se détérioraient parfois suffisamment pour créer un incident (Par exemple, en janvier 1793, exaspéré par le botaniste Labillardière*, l'officier Bonvouloir jeta deux bouteilles sur le savant qui prenait son petit-déjeuner). Cette tâche fut rendue d'autant plus ardue pour d’Entrecasteaux et ses successeurs par les exigences divergentes des naturalistes et par les divisions politiques entre les savants. Labillardière, Riche* et, après quelques hésitations, Ventenat*, étaient républicains tandis que d'autres soutenaient la cause royaliste. Malgré ces diverses sensibilités politiques, d’Entrecasteaux encouragea le travail de ses naturalistes et les incita à se spécialiser dans des domaines spécifiques pour éviter les doublons et les interférences dans leurs recherches. De plus, en attirant l'attention sur la mission de découverte et d'histoire naturelle de son voyage, d’Entrecasteaux accrut le zèle de ses officiers. Dans ses mémoires, Jurien de La Gravière* rapporte que ‘les naturalistes nous inoculent la passion des collections. Chacun à bord avait la sienne. La recherche de coquillages était la dominante. Les savants s'inquiètent de rivaux potentiels qui pourraient découvrir de nouvelles espèces et leur voler la vedette. Ils adressent leurs plaintes à l'Amiral, et il nous demanda de leur soumettre le résultat de toutes nos pêches. Cet ordre, comme vous pouvez l'imaginer, n'eut pour seul effet que de nous faire cacher nos trésors plus précieusement que jamais’[1].",
        'dentre-text-p5': "Des officiers, comme Jurien, et des savants comme l'aumônier bénédictin Ambroise Pierson* étaient d'une disposition conciliante, et la plupart des marins ne se préoccupaient pas de politique. Ensemble, ils contribuèrent à apaiser les tensions au sein de l'équipage.",
        'dentre-text-p6': "Les lieux visités et nommés par l'expédition d’Entrecasteaux étaient évidemment déjà bien connus, identifiés et désignés d'une manière ou d'une autre par les communautés aborigènes locales. Pourtant, bien que l'équipage en ait rencontré certains à plusieurs reprises[2], les Français ne se sont pas enquis auprès des aborigènes de la manière dont ils nommaient leur terre et les noms des lieux relevés par les membres de l'expédition. Cette pratique de dénomination unilatérale était liée au concept européen de ‘première découverte’ et aux fantasmes des Lumières européennes qui suggéraient aux visiteurs que les natifs (du moins ceux qu'ils rencontrèrent en Tasmanie en termes amicaux) étaient des ‘bons sauvages’ vivant dans un état ‘primitif’ originel non corrompu par la civilisation et ignorant des développements scientifiques et techniques en Europe.",
        
        // --- Page Carte Baudin ---
        'baudin-title': "Carte Interactive : L'Expédition de Nicolas Baudin (1800-1804)", 'baudin-desc': "Explorez les noms de lieux donnés lors de l'expédition scientifique de Nicolas Baudin...", 'map-title-baudin': "Carte de Baudin, 1802",

        // --- Page Ressources ---
        'resources-title': "Ressources", 'resources-p1': "Cette page contiendra des ressources additionnelles...", 'resources-p2': "<em>(Contenu à ajouter)</em>",

        // --- Étiquettes pour les fiches des cartes (Popups) ---
        'popup-french-name': "Nom français :", 'popup-ause-name': "Nom AusE :", 'popup-indigenous-name': "En", 'popup-coordinates': "Coordonnées :", 'popup-characteristic': "Caractéristique :", 'popup-details-link': "Pour un compte-rendu détaillé et les références, cliquez ici."
    },
    'en': {
        // --- General text ---
        'hero-title': "French Names Along the Australian Coastline", 'hero-subtitle': "The toponyms originated by the d’Entrecasteaux (1791-1794) and Baudin (1800-1804) voyages",
        'nav-home': "Home", 'nav-map-dentre': "Interactive Map: d'Entrecasteaux", 'nav-map-baudin': "Interactive Map: Baudin", 'nav-resources': "Resources",
        'footer-text': '&copy; 2024 - Dany Bréelle - "French Names Along the Australian Coastline" Project',

        // --- Homepage (index.html) ---
        'intro-title': "Introduction",
        'intro-p1': "This project explores the distinctive legacy of French place naming along Australia’s coastlines, tracing how these toponyms—many still visible on modern maps—reflect the layered histories of European exploration. Set against the backdrop of First Nations peoples’ deep and enduring connection to Country, the French naming practices sit alongside those of Dutch and British navigators, forming a complex palimpsest of meaning and memory.",
        'intro-p2': "By focusing on the over 670 sites named during the expeditions of d’Entrecasteaux and Baudin, the study brings to light a unique French perspective that enriches our understanding of Australia’s coastal history and its entangled global and local contexts.",
        'intro-p3': "<em>The research in this website was supported by the RGSSA, the WAHF, …</em>",
        'map-title-freycinet': "Map by Freycinet, 1812", 'map-title-beautemps': "Map by Beautemps-Beaupré, 1807",

        // --- d'Entrecasteaux Map Page ---
        'dentre-title': "Interactive Map: The d'Entrecasteaux Expedition (1791-1793)",
        'dentre-desc': "Explore the place names given during the expedition of Antoine Bruny d'Entrecasteaux, who charted in great detail the coasts of Tasmania in search of La Pérouse. Click on a marker to discover more information.",
        'dentre-text-p1': "The first object of the d’Entrecastreaux expedition, the search for the missing Lapérouse, ended in failure. They found no trace of his two ships or their crew on any islands in the western Pacific they sighted. However, the second parts of the expedition’s mission, the mapping of coasts in the Southern Lands still partially unknown to Europeans, proved highly successful. These discoveries gave new hope and motivation to the crew after a difficult crossing of the southern Indian Ocean in rough sea. D'Entrecasteaux's nomenclature bestowed along the coasts of what is now known as Tasmania and Western Australia pays tribute to his deserving crew who made these discoveries possible, and the voyage in general.",
        'dentre-text-p2': "The east coasts of Van Diemen Land (Tasmania) coasts were visited in April-May 1792 and again in late January-February 1793, and the south-west coasts of New Holland (Western Australia) in late December 1792 - January 1793.",
        'dentre-text-p3': "68 places were named along these coasts by d’Entrecasteaux and, after the voyage, for a couple of them, by Rossel*. They have been subdivided into two sections: the names on the east coasts of Van Diemen Land (Tasmania) coasts visited in April-May 1792 and again in late January-February 1793, and the names along the south-west coasts of New Holland (Western Australia) in late December 1792 - January 1793.",
        'dentre-text-p4': "It had not been an easy task for the commander to find common ground between nautical issues, the schedule of his itinerary, surveying and hydrographical work, and the focus of his savants on natural history and the discovery of new species. The naturalists were often complaining that the officers were given precedence (for example, they, the savants, had to wait far longer than the officers for the coxswain) and occasionally the relationships between officers and savants deteriorated enough to create an incident (For example, in January 1793, exasperated by the botanist Labillardière*, the officer Bonvouloir threw two bottles at the savant who was eating his breakfast). This task was made the more arduous for d’Entrecasteaux and his successors by the divergent requirements of the naturalists and by the political divisions between the savants. Labillardière, Riche* and, after some hesitation, Ventenat*, were republicans while others supported the royalist’s cause. Despite these various political hues, d’Entrecasteaux fostered the work of his naturalists and encouraged them to specialise in different specific areas to avoid duplication and interference with each other’s research work. In addition, by drawing attention on the discovery and natural history mission of his voyage, d’Entrecasteaux enhanced the zeal of his officers. In his memoirs, Jurien de La Gravière* reported that ‘the naturalists inoculate us with the passion for collections. Everyone on board had its own. The search for shells was the dominant one. The savants are worried about potential rivals who might discover new species and steal their thunder. They address their complaints to the Amiral, and he asked us to submit to them the result of all our fishing. This order, as you can imagine, had the sole effect to make us hide our treasures more closely than ever’[1].",
        'dentre-text-p5': "Officers, such as Jurien, and savants like the Benedictine chaplain Ambroise Pierson* were of a conciliatory disposition, and most of the sailors were not focusing on politics. Together, they contributed to ease tensions among the crew.",
        'dentre-text-p6': "The places visited and named by the d’Entrecasteaux expedition were obviously already well-known, identified and labelled in some way or another by the local aboriginal communities. Yet, despite the crew encountering some of them on several occasions[2], the French did not make inquiries of the aborigines on how they named their land and the names of the places surveyed by the members of the expedition. This one-sided naming practice was linked to the European concept of ‘first discovery’, and the fantasies of the European Enlightenment which suggested to the visitors that natives (at least the natives they met in Tasmania in friendly terms) were ‘noble savages’ living in an original ‘primitive’ state uncorrupted by civilization and ignorant of scientific and technical developments in Europe.",
        
        // --- Baudin Map Page ---
        'baudin-title': "Interactive Map: The Nicolas Baudin Expedition (1800-1804)", 'baudin-desc': "Explore the place names given during the scientific expedition of Nicolas Baudin...", 'map-title-baudin': "Map from Baudin expedition, 1802",

        // --- Resources Page ---
        'resources-title': "Resources", 'resources-p1': "This page will contain additional resources...", 'resources-p2': "<em>(Content to be added)</em>",
        
        // --- Labels for Map Popups ---
        'popup-french-name': "French name:", 'popup-ause-name': "AusE name:", 'popup-indigenous-name': "In", 'popup-coordinates': "Coordinates:", 'popup-characteristic': "Characteristic:", 'popup-details-link': "For a detailed account and references, click here."
    }
};
