// js/translations.js
const translations = {
    'fr': {
        // --- Textes généraux ---
        'hero-title': "Noms Français le long de la côte Australienne", 'hero-subtitle': "Les toponymes issus des voyages de d’Entrecasteaux (1791-1794) et Baudin (1800-1804)",
        'nav-home': "Accueil", 'nav-map-dentre': "Carte Interactive : d'Entrecasteaux", 'nav-map-baudin': "Carte Interactive : Baudin", 'nav-resources': "Ressources",
        'footer-text': '&copy; 2024 - Dany Bréelle - Projet "Noms Français le long de la côte Australienne"',

        // --- Page d'accueil (index.html) ---
        'intro-title': "Introduction",
        'intro-p1': "Ce projet explore l'héritage distinctif de la toponymie française le long des côtes australiennes, retraçant comment ces noms de lieux — dont beaucoup sont encore visibles sur les cartes modernes — reflètent les histoires superposées de l'exploration européenne. Dans le contexte du lien profond et durable des peuples des Premières Nations avec leur Territoire, les pratiques de dénomination françaises côtoient celles des navigateurs néerlandais et britanniques, formant un palimpseste complexe de sens et de mémoire.",
        'intro-p2': "En se concentrant sur les plus de 670 sites nommés lors des expéditions de d’Entrecasteaux et de Baudin, l'étude met en lumière une perspective française unique qui enrichit notre compréhension de l'histoire côtière de l'Australie et de ses contextes mondiaux et locaux enchevêtrés.",
        'intro-p3': "<em>La recherche présentée sur ce site a été soutenue par la RGSSA, la WAHF, …</em>",
        'map-title-freycinet': "Carte de Freycinet, 1812", 'map-title-beautemps': "Carte de Beautemps-Beaupré, 1807",

        // --- Page Carte d'Entrecasteaux ---
        'dentre-title': "Carte Interactive : L'Expédition d'Entrecasteaux (1791-1793)", 'dentre-desc': "Explorez les noms de lieux donnés lors de l'expédition d'Antoine Bruny d'Entrecasteaux, qui a cartographié en grand détail les côtes de la Tasmanie à la recherche de La Pérouse. Cliquez sur un marqueur pour découvrir plus d'informations.",
        'dentre-text-p1': "Le premier objectif de l'expédition d'Entrecasteaux, la recherche de La Pérouse, disparu, s'est soldé par un échec. Aucune trace de ses deux navires ou de leur équipage ne fut trouvée sur les îles du Pacifique occidental qu'ils explorèrent. Cependant, le second volet de la mission de l'expédition, la cartographie des côtes des Terres Australes encore partiellement inconnues des Européens, fut une grande réussite. Ces découvertes redonnèrent espoir et motivation à l'équipage après une traversée difficile de l'océan Indien austral dans une mer agitée. La nomenclature laissée par d'Entrecasteaux le long des côtes de ce qui est aujourd'hui la Tasmanie et l'Australie-Occidentale rend hommage à son équipage méritant qui a rendu ces découvertes possibles, ainsi qu'au voyage en général.",
        'dentre-text-p2': "Les côtes est de la Terre de Van Diemen (Tasmanie) furent visitées en avril-mai 1792 et de nouveau fin janvier-février 1793, et les côtes sud-ouest de la Nouvelle-Hollande (Australie-Occidentale) fin décembre 1792 - janvier 1793.",
        'dentre-text-p3': "68 lieux furent nommés le long de ces côtes par d’Entrecasteaux et, après le voyage, pour quelques-uns d'entre eux, par Rossel*. Ils ont été subdivisés en deux sections : les noms sur les côtes est de la Terre de Van Diemen (Tasmanie), visitées en avril-mai 1792 et de nouveau fin janvier-février 1793, et les noms le long des côtes sud-ouest de la Nouvelle-Hollande (Australie-Occidentale) fin décembre 1792 - janvier 1793.",
        'dentre-text-p4': "Ce ne fut pas une tâche facile pour le commandant de trouver un terrain d'entente entre les questions nautiques, le calendrier de son itinéraire, les travaux de relevé et d'hydrographie, et l'intérêt de ses savants pour l'histoire naturelle et la découverte de nouvelles espèces. Les naturalistes se plaignaient souvent que les officiers avaient la priorité (par exemple, eux, les savants, devaient attendre bien plus longtemps que les officiers pour le canotier) et les relations entre officiers et savants se détérioraient parfois suffisamment pour créer un incident (Par exemple, en janvier 1793, exaspéré par le botaniste Labillardière*, l'officier Bonvouloir jeta deux bouteilles sur le savant qui prenait son petit-déjeuner). Cette tâche fut rendue d'autant plus ardue pour d’Entrecasteaux et ses successeurs par les exigences divergentes des naturalistes et par les divisions politiques entre les savants. Labillardière, Riche* et, après quelques hésitations, Ventenat*, étaient républicains tandis que d'autres soutenaient la cause royaliste. Malgré ces diverses sensibilités politiques, d’Entrecasteaux encouragea le travail de ses naturalistes et les incita à se spécialiser dans des domaines spécifiques pour éviter les doublons et les interférences dans leurs recherches. De plus, en attirant l'attention sur la mission de découverte et d'histoire naturelle de son voyage, d’Entrecasteaux accrut le zèle de ses officiers. Dans ses mémoires, Jurien de La Gravière* rapporte que ‘les naturalistes nous inoculent la passion des collections. Chacun à bord avait la sienne. La recherche de coquillages était la dominante. Les savants s'inquiètent de rivaux potentiels qui pourraient découvrir de nouvelles espèces et leur voler la vedette. Ils adressent leurs plaintes à l'Amiral, et il nous demanda de leur soumettre le résultat de toutes nos pêches. Cet ordre, comme vous pouvez l'imaginer, n'eut pour seul effet que de nous faire cacher nos trésors plus précieusement que jamais’[1].",
        'dentre-text-p5': "Des officiers, comme Jurien, et des savants comme l'aumônier bénédictin Ambroise Pierson* étaient d'une disposition conciliante, et la plupart des marins ne se préoccupaient pas de politique. Ensemble, ils contribuèrent à apaiser les tensions au sein de l'équipage.",
        'dentre-text-p6': "Les lieux visités et nommés par l'expédition d’Entrecasteaux étaient évidemment déjà bien connus, identifiés et désignés d'une manière ou d'une autre par les communautés aborigènes locales. Pourtant, bien que l'équipage en ait rencontré certains à plusieurs reprises[2], les Français ne se sont pas enquis auprès des aborigènes de la manière dont ils nommaient leur terre et les noms des lieux relevés par les membres de l'expédition. Cette pratique de dénomination unilatérale était liée au concept européen de ‘première découverte’ et aux fantasmes des Lumières européennes qui suggéraient aux visiteurs que les natifs (du moins ceux qu'ils rencontrèrent en Tasmanie en termes amicaux) étaient des ‘bons sauvages’ vivant dans un état ‘primitif’ originel non corrompu par la civilisation et ignorant des développements scientifiques et techniques en Europe.",
        
        // --- Page Carte Baudin ---
        'baudin-title': "Carte Interactive : L'Expédition de Nicolas Baudin (1800-1804)", 'baudin-desc': "Explorez les noms de lieux donnés lors de l'expédition scientifique de Nicolas Baudin...", 'map-title-baudin': "Carte de Baudin, 1802",

        // --- Page Ressources ---
        'resources-title': "Ressources", 'resources-p1': "Cette page contiendra des ressources additionnelles...", 'resources-p2': "<em>(Contenu à ajouter)</em>",

        // --- Page de détail Baie de la Recherche ---
        'detail-rb-title': "Baie de la Recherche / Recherche Bay",
        'detail-rb-fig-caption': "Fig.1. Baie de la Recherche, section de la carte ‘Carte particulière du Canal Dentrecasteaux, entre la terre méridionale d'Anthony Van Diemen et l'île Bruny…’, Par Beautemps-Beaupré, Charles François, in Atlas du voyage de Bruny d’Entrecasteaux... 1807, Planche 4. Bibliothèque Nationale d'Australie.",
        'detail-rb-fig-link': "https://nla.gov.au/nla.obj-230810562/view",
        'detail-rb-fig-legend': "Les tracés des navires et des canots ont été colorés différemment pour distinguer les campagnes hydrographiques de 1792 (bleu et rouge) de celles de 1793 (violet et vert).",
        'detail-rb-legend-north': "Nord",
        'detail-rb-legend-vessels1792': "Tracé des navires la Recherche et l’Espérance en 1792",
        'detail-rb-legend-longboats1792': "Tracé des canots en 1792",
        'detail-rb-legend-vessels1793': "Tracé des navires la Recherche et l’Espérance en 1793",
        'detail-rb-legend-longboats1793': "Tracé des canots en 1793",
        'detail-rb-heading1': "L'arrivée tumultueuse des frégates sur les côtes sud-est de la Tasmanie",
        'detail-rb-p1': "Les frégates atteignirent Ténériffe le 23 octobre, et le Cap de Bonne-Espérance le 16 février 1792. Initialement, l'expédition mit le cap sur les îles de l'Amirauté (au nord de la Nouvelle-Guinée) à la recherche d'informations sur l'expédition de La Pérouse, car des rumeurs au Cap suggéraient que des habitants de ces îles avaient été vus portant des uniformes et des accessoires navals français qui auraient pu provenir de l'expédition perdue. Le départ du Cap marqua le début de la mission officielle du voyage, commençant par le relevé des îles d'Amsterdam et de Saint-Paul (océan Indien). Les instructions de d'Entrecasteaux étaient de relever ensuite la côte sud-ouest de la Nouvelle-Hollande, avant d'atteindre la Nouvelle-Guinée[1]. Cependant, la force des vents d'ouest soufflant sans interruption pendant plusieurs semaines[2] et la mer extrêmement grosse mettaient 'les frégates à rude épreuve' et 'entraînaient des ruptures de chaînes' tandis que 'l'eau a pénétré dans les soutes des navires…'[3]. Dans ces circonstances et avec l'hiver imminent, le commandant, qui avait fait une mauvaise chute lors d'un violent roulis et s'était gravement blessé aux côtes (mars-début avril 1792), modifia pragmatiquement son itinéraire et se dirigea vers les côtes mieux protégées de l'est de la Tasmanie, alors connue sous le nom de Terre de Van Diemen (voir le glossaire).",
        'detail-rb-p2': "La côte sud-est de la Tasmanie fut aperçue pour la première fois le 20 avril 1792, et l'expédition entra le 23 avril 1792 dans une baie abritée (Baie de la Recherche*) où les frégates jetèrent l'ancre et furent réparées. Les maillons brisés entre la chaîne et le câble de l'ancre de <em>la Recherche</em>, qui 'avaient probablement été surchauffés par le métallurgiste qui l'avait forgée', furent réparés[4].",
        'detail-rb-heading2': "La dénomination du canal d’Entrecasteaux",
        'detail-rb-p3': "Pendant leur séjour, les hydrographes et les officiers préparèrent les premières cartes des côtes bordant le Canal d'Entrecasteaux* et nommèrent de nombreux lieux. Après leur départ le 28 mai, ils contournèrent l'Australie par une route lointaine via la Nouvelle-Calédonie, les îles Salomon, la Nouvelle-Irlande, l'île de l'Amirauté, Amboine, le Cap Leeuwin et la côte sud-ouest de la Nouvelle-Hollande, avant de retourner en Terre de Van Diemen pour cinq semaines, du 21 janvier au 27 février 1793, afin de compléter leur reconnaissance.",
        'detail-rb-p4': "Le long des rives de la Terre de Van Diemen, le commandant nomma certaines caractéristiques géographiques d'après les membres de son équipage qui avaient le plus contribué aux résultats des levés, surtout après que les canots de l'expédition eurent été envoyés pour cartographier les côtes rocheuses du canal, leurs baies et étudier leur histoire naturelle[5]. Finalement, 50 lieux de la Terre de Van Diemen reçurent un nom. Plus de la moitié de ces noms sont liés aux deux frégates de l'expédition, <em>la Recherche</em> et <em>l'Espérance</em> (Baie de la Recherche*, Port de l’Espérance*, etc.) et aux membres de l'équipage de l'expédition (23)[6]. 16 autres noms sont basés sur des emplacements géographiques (<em>Port du Nord Ouest</em>*…) et sur la géographie physique des côtes (<em>Baie de l'Isthme</em>*…). 5 autres noms évoquent la faune et la flore locales (Port des cygnes*…), et un nom fait référence à l'explorateur français Marion Dufresne dont les navires passèrent plusieurs jours dans la baie de Marion en Terre de Van Diemen en mars 1772.",
        'detail-rb-p5': "Ces trois cartes ci-dessous montrent des parties des côtes de la Terre de Van Diemen visitées par l'expédition. Elles sont ext
